
import { CharacterOption, SelectionOption } from './types';

export const MAIN_CHARACTERS: CharacterOption[] = [
  { id: 'mc_girl', name: 'Kız Çocuk', description: 'Hayal gücü geniş, mutlu bir kız çocuk', emoji: '👧', type: 'Main' },
  { id: 'mc_boy', name: 'Erkek Çocuk', description: 'Neşeli, oyun oynamayı seven bir hacker çocuk', emoji: '👦', type: 'Main' },
  { id: 'mc_police', name: 'Yardımsever Polis', description: 'Mavi üniformalı, herkese yardım eden ve trafiği düzenleyen sevimli bir polis', emoji: '👮', type: 'Main' },
  { id: 'mc_superhero', name: 'Süper Kahraman', description: 'Renkli peleriniyle gökyüzünde uçan ve yardıma ihtiyacı olanlara koşan güçlü bir kahraman', emoji: '🦸', type: 'Main' },
  { id: 'mc_explorer', name: 'Küçük Kaşif', description: 'Sırt çantalı, izci şapkası ve büyüteci olan maceracı bir izci çocuk', emoji: '🎒', type: 'Main' },
  { id: 'mc_robot', name: 'Mini Robot', description: 'Renkli düğmeleri olan sevimli bir robot', emoji: '🤖', type: 'Main' },
  { id: 'mc_dragon', name: 'Minik Ejderha', description: 'Uçmayı yeni öğrenen şirin bir ejderha', emoji: '🐉', type: 'Main' },
  { id: 'mc_lion', name: 'Cesur Aslan', description: 'Yelesi pırıl pırıl parlayan cesur bir aslan', emoji: '🦁', type: 'Main' },
  { id: 'mc_fairy', name: 'Işık Perisi', description: 'Her yere ışıltı saçan minik bir peri', emoji: '🧚‍♀️', type: 'Main' },
  { id: 'mc_fox', name: 'Yaramaz Tilki', description: 'Kurnaz ama iyi kalpli turuncu bir tilki', emoji: '🦊', type: 'Main' },
  { id: 'mc_alien', name: 'Sevimli Uzaylı', description: 'Üç gözlü, yeşil ve dost canlısı bir uzaylı', emoji: '👽', type: 'Main' },
  { id: 'mc_turtle', name: 'Bilge Kaplumbağa', description: 'Gözlüklü ve çok bilgili yaşlı bir kaplumbağa', emoji: '🐢', type: 'Main' },
  { id: 'mc_princess', name: 'Küçük Prenses', description: 'Sihirli tacı olan nazik bir prenses', emoji: '👸', type: 'Main' },
  { id: 'mc_prince', name: 'Küçük Prens', description: 'Kendi gezegeninden gelen altın saçlı bir prens', emoji: '👑', type: 'Main' },
  { id: 'mc_wizard', name: 'Genç Büyücü', description: 'Yıldızlı pelerini olan yetenekli bir büyücü', emoji: '🧙‍♂️', type: 'Main' },
  { id: 'mc_planet', name: 'Gezegen', description: 'Kolları ve yüzü olan, konuşan neşeli bir gezegen', emoji: '🪐', type: 'Main' },
  { id: 'mc_detective', name: 'Dedektif', description: 'Büyüteciyle gizemleri çözen minik bir dedektif', emoji: '🕵️', type: 'Main' },
  { id: 'mc_firefighter', name: 'Cesur İtfaiyeci', description: 'Kırmızı kamyonu ve kaskı olan yardımsever bir itfaiyeci', emoji: '👨‍🚒', type: 'Main' },
  { id: 'mc_bear', name: 'Oyuncak Ayı', description: 'Canlanan pofuduk bir oyuncak ayı', emoji: '🧸', type: 'Main' },
  { id: 'mc_pirate', name: 'Korsan', description: 'Tek gözü kapalı, şapkası ve tahta bacağı olan maceracı bir korsan', emoji: '🏴‍☠️', type: 'Main' },
];

export const SIDE_CHARACTERS: CharacterOption[] = [
  { id: 'sc_none', name: 'Yan karakter istemiyorum', description: 'Yalnız macera', emoji: '🚫', type: 'Side' },
  { id: 'sc_friend', name: 'Arkadaş', description: 'En yakın oyun arkadaşı', emoji: '🧒', type: 'Side' },
  { id: 'sc_fish', name: 'Uçan Balık', description: 'Kanatları olan gümüş renkli bir balık', emoji: '🐟', type: 'Side' },
  { id: 'sc_owl', name: 'Akıllı Baykuş', description: 'Her şeyi bilen, gözlüklü bir baykuş', emoji: '🦉', type: 'Side' },
  { id: 'sc_rabbit', name: 'Minik Tavşan', description: 'Hızlı koşan, uzun kulaklı beyaz bir tavşan', emoji: '🐰', type: 'Side' },
  { id: 'sc_dog', name: 'Sevimli Köpek', description: 'Kuyruğunu sürekli sallayan sadık bir köpek', emoji: '🐶', type: 'Side' },
  { id: 'sc_bird', name: 'Altın Kuş', description: 'Tüyleri altından yapılmış gibi parlayan bir kuş', emoji: '🐦', type: 'Side' },
  { id: 'sc_squirrel', name: 'Zıpır Sincap', description: 'Meşe palamudu toplayan hareketli bir sincap', emoji: '🐿️', type: 'Side' },
  { id: 'sc_mermaid', name: 'Deniz Kızı', description: 'Parlak pulları olan şarkıcı bir deniz kızı', emoji: '🧜‍♀️', type: 'Side' },
  { id: 'sc_dino', name: 'Küçük Dino', description: 'Ot yemeyi seven minik, zararsız bir dinozor', emoji: '🦕', type: 'Side' },
  { id: 'sc_carpet', name: 'Uçan Halı', description: 'Desenli, konuşabilen sihirli bir halı', emoji: '🧞', type: 'Side' },
  { id: 'sc_star', name: 'Parlak Yıldız', description: 'Gökyüzünden inmiş, ışıl ışıl bir yıldız', emoji: '🌟', type: 'Side' },
  { id: 'sc_butterfly', name: 'Renkli Kelebek', description: 'Devasa kanatları olan rengarenk bir kelebek', emoji: '🦋', type: 'Side' },
  { id: 'sc_cat', name: 'Sevimli Kedi', description: 'Mırıl mırıl ses çıkaran yumuşak bir kedi', emoji: '🐱', type: 'Side' },
  { id: 'sc_wind', name: 'Rüzgar Perisi', description: 'Üfleyince fırtınalar çıkaran şeffaf bir peri', emoji: '🌬️', type: 'Side' },
  { id: 'sc_flying_turtle', name: 'Uçan Kaplumbağa', description: 'Kabuğunda pervanesi olan hızlı bir kaplumbağa', emoji: '🐢', type: 'Side' },
  { id: 'sc_villain', name: 'Kötü Karakter', description: 'Masalın karşı kahramanı/kötü kalpli karakteri', emoji: '🦹', type: 'Side' },
];

export const LOCATIONS: SelectionOption[] = [
  { id: 'loc_forest', name: 'Büyülü Orman', emoji: '🌲' },
  { id: 'loc_park', name: 'Park', emoji: '🛝' },
  { id: 'loc_space', name: 'Uzay Üssü', emoji: '🚀' },
  { id: 'loc_cloud_city', name: 'Renkli Bulut Şyehir', emoji: '☁️' },
  { id: 'loc_toy_land', name: 'Oyuncak Diyarı', emoji: '🧸' },
  { id: 'loc_cloud_land', name: 'Bulut Diyarı', emoji: '🌤️' },
  { id: 'loc_cave', name: 'Gizli Mağara', emoji: '🕳️' },
  { id: 'loc_snow', name: 'Kar Diyarı', emoji: '❄️' },
  { id: 'loc_city', name: 'Şehir', emoji: '🏙️' },
  { id: 'loc_school', name: 'Okul', emoji: '🏫' },
  { id: 'loc_ocean', name: 'Derin Okyanus Krallığı', emoji: '🌊' },
  { id: 'loc_time', name: 'Zaman Tüneli', emoji: '⏳' },
  { id: 'loc_workshop', name: 'Robot Atölyesi', emoji: '🤖' },
  { id: 'loc_garden', name: 'Peri Bahçesi', emoji: '🌷' },
  { id: 'loc_library', name: 'Gökyüzü Kütüphanesi', emoji: '📚' },
  { id: 'loc_dino_valley', name: 'Dinozor Vadisi', emoji: '🦖' },
  { id: 'loc_dream', name: 'Rüya Kasabası', emoji: '💤' },
];

export const THEMES: SelectionOption[] = [
  { id: 'th_dark', name: 'Karanlıktan Korkmamak', emoji: '🔦' },
  { id: 'th_lose', name: 'Kaybetmekten Korkmamak', emoji: '🎲' },
  { id: 'th_teeth', name: 'Diş Fırçalama Alışkanlığı', emoji: '🦷' },
  { id: 'th_school', name: 'Okulun İlk Günü Heyecanı', emoji: '🎒' },
  { id: 'th_sea', name: 'Denize Girmekten Korkmamak', emoji: '🏊' },
  { id: 'th_sleep', name: 'Tek Başına Uyuma', emoji: '🛌' },
  { id: 'th_brave', name: 'Cesaret ve Kendine Güven', emoji: '🦁' },
  { id: 'th_share', name: 'Paylaşmayı Öğrenme', emoji: '🤝' },
  { id: 'th_friend', name: 'Arkadaşlık ve İş Birliği', emoji: '👫' },
  { id: 'th_curious', name: 'Merak Etmek ve Soru Sormak', emoji: '❓' },
  { id: 'th_food', name: 'Yeni Tatlar Deneme', emoji: '🥦' },
  { id: 'th_toys', name: 'Oyuncakları Toplama', emoji: '🧺' },
  { id: 'th_feelings', name: 'Duyguları Tanıma', emoji: '🎭' },
  { id: 'th_patience', name: 'Sabretmek ve Sırasını Beklemek', emoji: '⏳' },
  { id: 'th_nature', name: 'Doğa ve Hayvanları Koruma', emoji: '🌳' },
  { id: 'th_fail', name: 'Başarısız Olmaktan Korkmamak', emoji: '💪' },
  { id: 'th_family', name: 'Aile ile Güven ve Sevgi Bağı', emoji: '❤️' },
];

export const VISUAL_STYLES: SelectionOption[] = [
  { id: 'style_modern_textured', name: 'Modern, Dokulu Çocuk Kitabı', emoji: '📖', prompt: "Modern, textured children's book illustration, whimsical, textured, crayon texture, flat design, colorful but muted earth tones, playful, abstract shapes, collage style, detailed background." },
  { id: 'style_disney', name: 'Disney Masalı', emoji: '🏰', prompt: "Classic Disney animation style, 2D hand-drawn look, expressive, magical." },
  { id: 'style_pixar', name: 'Pixar', emoji: '🎬', prompt: "3D Pixar animation style, realistic lighting, vibrant colors, clean renders." },
  { id: 'style_pixar_future', name: 'Pixar Future', emoji: '🚀', prompt: "Futuristic 3D Pixar animation style, neon accents, sleek surfaces, advanced lighting, cinematic sci-fi aesthetic for kids, high tech but friendly." },
  { id: 'style_anime', name: 'Anime / Manga', emoji: '🎌', prompt: "High-quality anime illustration style, cel-shaded, vibrant colors, expressive eyes, beautiful scenery, Studio Ghibli meets modern Makoto Shinkai aesthetic." },
  { id: 'style_casual', name: 'Casual Game Art', emoji: '🎮', prompt: "Professional casual mobile game art style, clean vector-like rendering, high contrast, glossy finish, cute proportions, inviting and polished." },
  { id: 'style_watercolor', name: 'Suluboya', emoji: '🎨', prompt: "Soft watercolor illustration, hand-painted texture, artistic, gentle." },
  { id: 'style_cartoon', name: 'Karikatür', emoji: '🤡', prompt: "Funny cartoon style, bold outlines, exaggerated features, bright colors." },
  { id: 'style_pixel', name: 'Piksel art', emoji: '👾', prompt: "Retro pixel art style, 16-bit aesthetic, nostalgic, blocky but cute." },
  { id: 'style_disney_jr', name: 'Disney Junior', emoji: '👶', prompt: "Disney Junior CGI style, soft rounded shapes, simple textures, bright for toddlers." },
  { id: 'style_dreamworks', name: 'Dreamworks', emoji: '🌙', prompt: "Dreamworks animation style, cinematic, detailed environments, expressive characters." },
  { id: 'style_ghibli', name: 'Ghibli', emoji: '🚂', prompt: "Studio Ghibli anime style, lush hand-painted backgrounds, soft character designs, whimsical." },
];
